### ISSUE TITLE
Move plugin content from addons/HTML5FileExchange to the root directory of the repository

### ISSUE THREAD

**Issue by OverloadedOrama** [Pukkah/HTML5-File-Exchange-for-Godot#1]
Hello, and thanks for developing this useful plugin! I would like to suggest that you move the content from addons/HTML5FileExchange and put it in the root directory of the repo. That would allow us to include your repository as a submodule for our projects. [See this](https://github.com/Orama-Interactive/Pixelorama/tree/master/addons) as an example.

**Comment by Pukkah** [comment]
It's planned to publish the plugin in Godot's Asset Library once it's a little bit more polished. As far as I understand - folder structure must be present for it to get properly imported into projects.
If you know how to still achieve that while moving contents to root directory - let me know and I'll consider moving it.

**Comment by OverloadedOrama** [comment]
Oh, I'm not sure how the asset library works to be honest. I suggested moving the contents because I was thinking of creating a submodule of this repository to my own repo, which would make it easy for me to keep up to date with the changes you make. But I suppose the asset library could help with the same thing, so that works for me. Thank you!
